#!/usr/bin/env node

process.title = 'dflow'

const actions = require('./actions')
const debug = require('debug')('dflow')
const nopt = require('nopt')
const pkg = require('../../package.json')
const usage = require('./usage')

// Do not crash on errors.
process.on('uncaughtException', (error) => console.error(error.stack))

const edit = actions.edit
const run = actions.run
const validate = actions.validate

const knownOpts = {
  help: Boolean,
  version: Boolean
}

const shortHandOpts = {
  h: '--help'
}

const args = process.argv

const opt = nopt(knownOpts, shortHandOpts, args, 2)

if (opt.version) {
  console.log(pkg.version)
  process.exit(0)
}

const remain = opt.argv.remain

if (remain.length === 0) {
  // Show help.
  if (opt.help) {
    console.log(usage)
    process.exit(0)
  }
}

switch (remain[0]) {
  case 'edit':
    debug('action is edit')
    edit(args)
    break

  case 'run':
    debug('action is run')
    run(args)
    break

  case 'validate':
    debug('action is validate')
    validate(args)
    break

  default:
    debug('action is edit')
    edit(args)
}
