#!/usr/bin/env node

process.title = 'dflow'

var nopt = require('nopt')

var pkg = require('../../package.json')
var usage = require('./usage')
var actions = require('./actions')

var edit = actions.edit
var validate = actions.validate

var knownOpts = {
  help: Boolean,
  version: Boolean
}

var shortHandOpts = {
  h: '--help'
}

var args = process.argv

var opt = nopt(knownOpts, shortHandOpts, args, 2)

if (opt.help) {
  console.log(usage)
  process.exit(0)
}

if (opt.version) {
  console.log(pkg.version)
  process.exit(0)
}

var remain = opt.argv.remain

// Default action is *edit*
if (remain.length === 0) edit(args)

if (remain[0] === 'edit') edit(args)

if (remain[0] === 'validate') validate(args)
