
domain: g14n.info

gems:
  - jekyll-sitemap

markdown: kramdown

collections:
  examples:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: common/page

nav:
  Examples: /dflow/examples
  API: /dflow/api
  CLI: /dflow/cli
  Specification: /dflow/specification
  Contributing: /dflow/contributing
